<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f7f5;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .container {
            background-color: #ffffff;
            border-radius: 8px;
            padding: 30px;
            max-w-2xl: 600px;
            margin: 0 auto;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        h2 {
            color: #031b4e;
            margin-top: 0;
        }
        .alert {
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            font-weight: bold;
        }
        .alert-warning {
            background-color: #fff3cd;
            color: #856404;
            border: 1px solid #ffeeba;
        }
        .alert-danger {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }
        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .details-table th, .details-table td {
            text-align: left;
            padding: 10px;
            border-bottom: 1px solid #eee;
        }
        .details-table th {
            color: #666;
            font-weight: normal;
        }
        .footer {
            margin-top: 30px;
            font-size: 12px;
            color: #999;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Payment Reminder</h2>
        
        <p>Dear {{ $details['name'] }},</p>
        
        <div class="alert {{ $details['is_overdue'] ? 'alert-danger' : 'alert-warning' }}">
            {{ $details['status_text'] }}
        </div>
        
        <p>This is an automated reminder regarding your payment profile for <strong>{{ $details['assignment'] }}</strong>.</p>
        
        <table class="details-table">
            <tr>
                <th>Amount Due:</th>
                <td style="font-weight: bold; color: #000;">₹{{ number_format($details['amount'], 2) }}</td>
            </tr>
            <tr>
                <th>Due Date:</th>
                <td>{{ \Carbon\Carbon::parse($details['due_date'])->format('d M, Y') }}</td>
            </tr>
        </table>
        
        <p>If you have already made this payment, please disregard this email. Otherwise, kindly complete the payment at your earliest convenience.</p>
        
        <p>Thank you,</p>
        <p><strong>Warriors Educare Administration</strong></p>
        
        <div class="footer">
            This is an automated message generated by the Warriors Educare Portal. Please do not reply directly to this email.
        </div>
    </div>
</body>
</html>
